### ISSUE TITLE
error: attribute 'com.domain.package:progressIndeterminate' not found.

### ISSUE THREAD

**Issue by softmarshmallow** [thomper/sweet-alert-dialog#4]
added to gradle, synced. wont work

Good work by btw.
supporting dead library is awesome!

`error: attribute 'com.bridged_lab.bridged:progressIndeterminate' not found.`

what should i do?

**Comment by thomper** [comment]
Sadly I don't have time to maintain this repo properly.  I believe F0RIS keeps a well-maintained fork available here: https://github.com/F0RIS/sweet-alert-dialog
