### ISSUE TITLE
Dialog button text visible only half 

### ISSUE THREAD

**Issue by mortuzahossain** [thomper/sweet-alert-dialog#6]
Due to padding issue the dialog action button not fully visible like ___~OK~___ upper part only visible and the lower part is not visible.

**Comment by mortuzahossain** [comment]
I am using the material theme.

**Comment by enriquejuan2** [comment]
I have the same problem, did you manage to solve it?

**Comment by thomper** [comment]
This fork's not maintained, please use F0RIS' instead: https://github.com/F0RIS/sweet-alert-dialog
